nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
#         '^/':
#             allow_origin: ['virtualhost']

# nelmio_cors:
#     defaults:
#         allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#     paths:
        '^/ville/': # Spécifiez les chemins où vous souhaitez appliquer les règles CORS
            allow_origin: ['https://127.0.0.1:8000', 'https://localhost:8000']
            allow_methods: ['GET', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600

